/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 capybaras.glb 
Author: Peiwen.Wu (https://sketchfab.com/Peiwen.Wu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/quill-capybara-09afafe663f24020972d26380892700a
Title: Quill - Capybara
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Capybaras(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/models/capybaras.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="f01b0bba450d49fd964495bb9db16447fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="BakedMesh">
                  <group name="Root">
                    <group name="InitialSpawnArea" />
                    <group name="NewLayer0">
                      <group name="NewLayer0_0000">
                        <mesh name="NewLayer0_0000_Single_Sided_Material_0" geometry={nodes.NewLayer0_0000_Single_Sided_Material_0.geometry} material={materials.Single_Sided_Material} />
                        <mesh name="NewLayer0_0000_Single_Sided_Material_0_1" geometry={nodes.NewLayer0_0000_Single_Sided_Material_0_1.geometry} material={materials.Single_Sided_Material} />
                        <mesh name="NewLayer0_0000_Single_Sided_Material_0_2" geometry={nodes.NewLayer0_0000_Single_Sided_Material_0_2.geometry} material={materials.Single_Sided_Material} />
                        <mesh name="NewLayer0_0000_Double_Sided_Material_0" geometry={nodes.NewLayer0_0000_Double_Sided_Material_0.geometry} material={materials.Double_Sided_Material} />
                      </group>
                    </group>
                    <group name="Spring">
                      <group name="Spring_0000">
                        <mesh name="Spring_0000_Double_Sided_Material_0" geometry={nodes.Spring_0000_Double_Sided_Material_0.geometry} material={materials.Double_Sided_Material} />
                        <mesh name="Spring_0000_Single_Sided_Material_0" geometry={nodes.Spring_0000_Single_Sided_Material_0.geometry} material={materials.Single_Sided_Material} />
                      </group>
                      <group name="Spring_0001">
                        <mesh name="Spring_0001_Double_Sided_Material_0" geometry={nodes.Spring_0001_Double_Sided_Material_0.geometry} material={materials.Double_Sided_Material} />
                        <mesh name="Spring_0001_Single_Sided_Material_0" geometry={nodes.Spring_0001_Single_Sided_Material_0.geometry} material={materials.Single_Sided_Material} />
                      </group>
                      <group name="Spring_0002">
                        <mesh name="Spring_0002_Double_Sided_Material_0" geometry={nodes.Spring_0002_Double_Sided_Material_0.geometry} material={materials.Double_Sided_Material} />
                        <mesh name="Spring_0002_Single_Sided_Material_0" geometry={nodes.Spring_0002_Single_Sided_Material_0.geometry} material={materials.Single_Sided_Material} />
                      </group>
                      <group name="Spring_0003">
                        <mesh name="Spring_0003_Double_Sided_Material_0" geometry={nodes.Spring_0003_Double_Sided_Material_0.geometry} material={materials.Double_Sided_Material} />
                        <mesh name="Spring_0003_Single_Sided_Material_0" geometry={nodes.Spring_0003_Single_Sided_Material_0.geometry} material={materials.Single_Sided_Material} />
                      </group>
                      <group name="Spring_0004">
                        <mesh name="Spring_0004_Double_Sided_Material_0" geometry={nodes.Spring_0004_Double_Sided_Material_0.geometry} material={materials.Double_Sided_Material} />
                        <mesh name="Spring_0004_Single_Sided_Material_0" geometry={nodes.Spring_0004_Single_Sided_Material_0.geometry} material={materials.Single_Sided_Material} />
                      </group>
                      <group name="Spring_0005">
                        <mesh name="Spring_0005_Double_Sided_Material_0" geometry={nodes.Spring_0005_Double_Sided_Material_0.geometry} material={materials.Double_Sided_Material} />
                        <mesh name="Spring_0005_Single_Sided_Material_0" geometry={nodes.Spring_0005_Single_Sided_Material_0.geometry} material={materials.Single_Sided_Material} />
                      </group>
                      <group name="Spring_0006">
                        <mesh name="Spring_0006_Double_Sided_Material_0" geometry={nodes.Spring_0006_Double_Sided_Material_0.geometry} material={materials.Double_Sided_Material} />
                        <mesh name="Spring_0006_Single_Sided_Material_0" geometry={nodes.Spring_0006_Single_Sided_Material_0.geometry} material={materials.Single_Sided_Material} />
                      </group>
                      <group name="Spring_0007">
                        <mesh name="Spring_0007_Double_Sided_Material_0" geometry={nodes.Spring_0007_Double_Sided_Material_0.geometry} material={materials.Double_Sided_Material} />
                        <mesh name="Spring_0007_Single_Sided_Material_0" geometry={nodes.Spring_0007_Single_Sided_Material_0.geometry} material={materials.Single_Sided_Material} />
                      </group>
                      <group name="Spring_0008">
                        <mesh name="Spring_0008_Double_Sided_Material_0" geometry={nodes.Spring_0008_Double_Sided_Material_0.geometry} material={materials.Double_Sided_Material} />
                        <mesh name="Spring_0008_Single_Sided_Material_0" geometry={nodes.Spring_0008_Single_Sided_Material_0.geometry} material={materials.Single_Sided_Material} />
                      </group>
                      <group name="Spring_0009">
                        <mesh name="Spring_0009_Double_Sided_Material_0" geometry={nodes.Spring_0009_Double_Sided_Material_0.geometry} material={materials.Double_Sided_Material} />
                        <mesh name="Spring_0009_Single_Sided_Material_0" geometry={nodes.Spring_0009_Single_Sided_Material_0.geometry} material={materials.Single_Sided_Material} />
                      </group>
                      <group name="Spring_0010">
                        <mesh name="Spring_0010_Double_Sided_Material_0" geometry={nodes.Spring_0010_Double_Sided_Material_0.geometry} material={materials.Double_Sided_Material} />
                        <mesh name="Spring_0010_Single_Sided_Material_0" geometry={nodes.Spring_0010_Single_Sided_Material_0.geometry} material={materials.Single_Sided_Material} />
                      </group>
                      <group name="Spring_0011">
                        <mesh name="Spring_0011_Double_Sided_Material_0" geometry={nodes.Spring_0011_Double_Sided_Material_0.geometry} material={materials.Double_Sided_Material} />
                        <mesh name="Spring_0011_Single_Sided_Material_0" geometry={nodes.Spring_0011_Single_Sided_Material_0.geometry} material={materials.Single_Sided_Material} />
                      </group>
                      <group name="Spring_0012">
                        <mesh name="Spring_0012_Double_Sided_Material_0" geometry={nodes.Spring_0012_Double_Sided_Material_0.geometry} material={materials.Double_Sided_Material} />
                        <mesh name="Spring_0012_Single_Sided_Material_0" geometry={nodes.Spring_0012_Single_Sided_Material_0.geometry} material={materials.Single_Sided_Material} />
                      </group>
                      <group name="Spring_0013">
                        <mesh name="Spring_0013_Double_Sided_Material_0" geometry={nodes.Spring_0013_Double_Sided_Material_0.geometry} material={materials.Double_Sided_Material} />
                        <mesh name="Spring_0013_Single_Sided_Material_0" geometry={nodes.Spring_0013_Single_Sided_Material_0.geometry} material={materials.Single_Sided_Material} />
                      </group>
                      <group name="Spring_0014">
                        <mesh name="Spring_0014_Double_Sided_Material_0" geometry={nodes.Spring_0014_Double_Sided_Material_0.geometry} material={materials.Double_Sided_Material} />
                        <mesh name="Spring_0014_Single_Sided_Material_0" geometry={nodes.Spring_0014_Single_Sided_Material_0.geometry} material={materials.Single_Sided_Material} />
                      </group>
                    </group>
                    <group name="NewLayer1">
                      <group name="NewLayer1_0000">
                        <mesh name="NewLayer1_0000_Single_Sided_Material_0" geometry={nodes.NewLayer1_0000_Single_Sided_Material_0.geometry} material={materials.Single_Sided_Material} />
                      </group>
                    </group>
                    <group name="Pigs">
                      <group name="Pigs_0000">
                        <mesh name="Pigs_0000_Single_Sided_Material_0" geometry={nodes.Pigs_0000_Single_Sided_Material_0.geometry} material={materials.Single_Sided_Material} />
                        <mesh name="Pigs_0000_Single_Sided_Material_0_1" geometry={nodes.Pigs_0000_Single_Sided_Material_0_1.geometry} material={materials.Single_Sided_Material} />
                        <mesh name="Pigs_0000_Single_Sided_Material_0_2" geometry={nodes.Pigs_0000_Single_Sided_Material_0_2.geometry} material={materials.Single_Sided_Material} />
                        <mesh name="Pigs_0000_Single_Sided_Material_0_3" geometry={nodes.Pigs_0000_Single_Sided_Material_0_3.geometry} material={materials.Single_Sided_Material} />
                        <mesh name="Pigs_0000_Single_Sided_Material_0_4" geometry={nodes.Pigs_0000_Single_Sided_Material_0_4.geometry} material={materials.Single_Sided_Material} />
                        <mesh name="Pigs_0000_Single_Sided_Material_0_5" geometry={nodes.Pigs_0000_Single_Sided_Material_0_5.geometry} material={materials.Single_Sided_Material} />
                        <mesh name="Pigs_0000_Single_Sided_Material_0_6" geometry={nodes.Pigs_0000_Single_Sided_Material_0_6.geometry} material={materials.Single_Sided_Material} />
                        <mesh name="Pigs_0000_Double_Sided_Material_0" geometry={nodes.Pigs_0000_Double_Sided_Material_0.geometry} material={materials.Double_Sided_Material} />
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/capybaras.glb')
