/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 japanese_restaurant.glb 
Author: annzep (https://sketchfab.com/annzep)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/japanese-restaurant-9b3c5076541148fca229edeb1a1b07ef
Title: Japanese Restaurant
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Japan(props) {
  const { nodes, materials } = useGLTF('/models/japanese_restaurant.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.polySurface113_lambert1_0.geometry} material={materials.lambert1} position={[0, 0, -1.551]} />
      <group position={[0, 0.265, 0]}>
        <mesh geometry={nodes.polySurface513_lambert32_0.geometry} material={materials.lambert32} />
        <mesh geometry={nodes.polySurface514_lambert32_0.geometry} material={materials.lambert32} />
        <mesh geometry={nodes.polySurface515_lambert32_0.geometry} material={materials.lambert32} />
        <mesh geometry={nodes.polySurface516_lambert32_0.geometry} material={materials.lambert32} />
        <mesh geometry={nodes.polySurface517_lambert32_0.geometry} material={materials.lambert32} />
        <mesh geometry={nodes.polySurface518_lambert32_0.geometry} material={materials.lambert32} />
        <mesh geometry={nodes.polySurface519_lambert32_0.geometry} material={materials.lambert32} />
        <mesh geometry={nodes.polySurface520_lambert32_0.geometry} material={materials.lambert32} />
        <mesh geometry={nodes.polySurface521_lambert32_0.geometry} material={materials.lambert32} />
        <mesh geometry={nodes.polySurface522_lambert40_0.geometry} material={materials.lambert40} />
        <mesh geometry={nodes.polySurface523_lambert32_0.geometry} material={materials.lambert32} />
        <mesh geometry={nodes.polySurface524_lambert32_0.geometry} material={materials.lambert32} />
        <mesh geometry={nodes.polySurface525_lambert32_0.geometry} material={materials.lambert32} />
      </group>
      <group position={[8.522, 0, -11.334]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.polySurface526_lambert32_0.geometry} material={materials.lambert32} />
        <mesh geometry={nodes.polySurface527_lambert32_0.geometry} material={materials.lambert32} />
        <mesh geometry={nodes.polySurface528_lambert32_0.geometry} material={materials.lambert32} />
        <mesh geometry={nodes.polySurface529_lambert32_0.geometry} material={materials.lambert32} />
        <mesh geometry={nodes.polySurface530_lambert32_0.geometry} material={materials.lambert32} />
        <mesh geometry={nodes.polySurface531_lambert32_0.geometry} material={materials.lambert32} />
        <mesh geometry={nodes.polySurface532_lambert32_0.geometry} material={materials.lambert32} />
        <mesh geometry={nodes.polySurface533_lambert32_0.geometry} material={materials.lambert32} />
        <mesh geometry={nodes.polySurface534_lambert32_0.geometry} material={materials.lambert32} />
        <mesh geometry={nodes.polySurface535_lambert40_0.geometry} material={materials.lambert40} />
        <mesh geometry={nodes.polySurface536_lambert32_0.geometry} material={materials.lambert32} />
        <mesh geometry={nodes.polySurface537_lambert32_0.geometry} material={materials.lambert32} />
        <mesh geometry={nodes.polySurface538_lambert32_0.geometry} material={materials.lambert32} />
      </group>
      <group position={[-0.022, 0, -6.308]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.polySurface652_lambert4_0.geometry} material={materials.lambert4} />
        <mesh geometry={nodes.polySurface653_phong6_0.geometry} material={materials.phong6} />
        <mesh geometry={nodes.polySurface654_phong6_0.geometry} material={materials.phong6} />
        <mesh geometry={nodes.polySurface655_lambert4_0.geometry} material={materials.lambert4} />
        <mesh geometry={nodes.polySurface656_lambert4_0.geometry} material={materials.lambert4} />
        <mesh geometry={nodes.polySurface657_phong6_0.geometry} material={materials.phong6} />
      </group>
      <group position={[-0.071, 0, 0]}>
        <mesh geometry={nodes.polySurface99_lambert4_0.geometry} material={materials.lambert4} position={[-0.052, -0.015, 0]} />
        <mesh geometry={nodes.polySurface100_lambert12_0.geometry} material={materials.lambert12} />
        <mesh geometry={nodes.polySurface101_lambert4_0.geometry} material={materials.lambert4} position={[0.071, -0.022, 0]} />
        <mesh geometry={nodes.polySurface102_lambert12_0.geometry} material={materials.lambert12} />
      </group>
      <group position={[1.653, 8.537, 2.48]} rotation={[1.449, 0, Math.PI / 2]} scale={[0.589, 1.274, 2.295]}>
        <mesh geometry={nodes.pCube140_lambert32_0.geometry} material={materials.lambert32} />
        <mesh geometry={nodes.pCube140_lambert33_0.geometry} material={materials.lambert33} />
      </group>
      <group position={[0.123, 8.564, 2.586]} rotation={[-0.122, 0, 0]} scale={[4.644, 1.779, 0.025]}>
        <mesh geometry={nodes.pCube154_lambert11_0.geometry} material={materials.lambert11} />
        <mesh geometry={nodes.pCube154_lambert10_0.geometry} material={materials.lambert10} />
      </group>
      <group position={[-6.976, 8.494, 3.528]} scale={[0.039, 0.893, 1.051]}>
        <mesh geometry={nodes.pCube155_lambert14_0.geometry} material={materials.lambert14} />
        <mesh geometry={nodes.pCube155_lambert15_0.geometry} material={materials.lambert15} />
      </group>
      <group position={[-1.644, 3.381, 2.533]} rotation={[0, Math.PI / 2, 0]} scale={[0.223, 1, 1.192]}>
        <mesh geometry={nodes.pCube159_lambert12_0.geometry} material={materials.lambert12} />
        <mesh geometry={nodes.pCube159_lambert13_0.geometry} material={materials.lambert13} />
      </group>
      <group position={[-0.008, 0.921, 0.025]} rotation={[0.057, 0.002, 0.099]}>
        <mesh geometry={nodes.polySurface260_lambert16_0.geometry} material={materials.lambert16} />
        <mesh geometry={nodes.polySurface260_lambert17_0.geometry} material={materials.lambert17} />
        <mesh geometry={nodes.polySurface261_lambert16_0.geometry} material={materials.lambert16} />
        <mesh geometry={nodes.polySurface262_lambert16_0.geometry} material={materials.lambert16} />
        <mesh geometry={nodes.polySurface263_lambert16_0.geometry} material={materials.lambert16} />
        <mesh geometry={nodes.polySurface264_lambert36_0.geometry} material={materials.lambert36} />
      </group>
      <group position={[0, 0, -0.198]}>
        <mesh geometry={nodes.polySurface255_lambert7_0.geometry} material={materials.lambert7} />
        <mesh geometry={nodes.polySurface255_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.polySurface255_lambert6_0.geometry} material={materials.lambert6} />
        <mesh geometry={nodes.polySurface255_lambert5_0.geometry} material={materials.lambert5} />
      </group>
      <group position={[0, 0, -0.037]}>
        <mesh geometry={nodes.polySurface259_lambert7_0.geometry} material={materials.lambert7} />
        <mesh geometry={nodes.polySurface259_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.polySurface259_lambert6_0.geometry} material={materials.lambert6} />
        <mesh geometry={nodes.polySurface259_lambert5_0.geometry} material={materials.lambert5} />
      </group>
      <group position={[-7.344, 8.494, 3.528]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.039, 0.893, 1.051]}>
        <mesh geometry={nodes.pCube205_lambert14_0.geometry} material={materials.lambert14} />
        <mesh geometry={nodes.pCube205_lambert15_0.geometry} material={materials.lambert15} />
      </group>
      <group position={[0, 0, -0.26]}>
        <mesh geometry={nodes.polySurface497_lambert36_0.geometry} material={materials.lambert36} />
        <mesh geometry={nodes.polySurface498_lambert8_0.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.polySurface498_lambert9_0.geometry} material={materials.lambert9} />
        <mesh geometry={nodes.polySurface499_lambert9_0.geometry} material={materials.lambert9} />
        <mesh geometry={nodes.polySurface500_lambert9_0.geometry} material={materials.lambert9} />
        <mesh geometry={nodes.polySurface501_lambert9_0.geometry} material={materials.lambert9} />
      </group>
      <group position={[2.108, -0.018, 11.635]} rotation={[-0.499, 1.311, 0.391]} scale={[0.599, 0.603, 0.599]}>
        <mesh geometry={nodes.polySurface434_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface435_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface436_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface437_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface438_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface439_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface440_lambert19_0.geometry} material={materials.lambert19} />
        <mesh geometry={nodes.polySurface441_lambert19_0.geometry} material={materials.lambert19} />
        <mesh geometry={nodes.polySurface442_lambert19_0.geometry} material={materials.lambert19} />
      </group>
      <group position={[4.117, 0.502, 11.771]} rotation={[-0.099, 1.419, -0.04]} scale={[0.599, 0.587, 0.599]}>
        <mesh geometry={nodes.polySurface395_lambert18_0.geometry} material={materials.lambert18} position={[-6.358, -3.189, -2.231]} scale={1.597} />
        <mesh geometry={nodes.polySurface396_lambert18_0.geometry} material={materials.lambert18} position={[-6.298, -3.181, -2.138]} scale={1.597} />
        <mesh geometry={nodes.polySurface397_lambert18_0.geometry} material={materials.lambert18} position={[-6.438, -3.206, -2.303]} scale={1.597} />
        <mesh geometry={nodes.polySurface398_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface399_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface400_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface401_lambert19_0.geometry} material={materials.lambert19} />
        <mesh geometry={nodes.polySurface402_lambert19_0.geometry} material={materials.lambert19} />
        <mesh geometry={nodes.polySurface403_lambert19_0.geometry} material={materials.lambert19} />
      </group>
      <group position={[11.987, -0.521, 9.439]} rotation={[-3.119, 0.271, 3.104]} scale={[0.599, 0.61, 0.599]}>
        <mesh geometry={nodes.polySurface425_lambert18_0.geometry} material={materials.lambert18} position={[-4.61, -2.312, -1.618]} scale={1.433} />
        <mesh geometry={nodes.polySurface426_lambert18_0.geometry} material={materials.lambert18} position={[-4.567, -2.306, -1.55]} scale={1.433} />
        <mesh geometry={nodes.polySurface427_lambert18_0.geometry} material={materials.lambert18} position={[-4.669, -2.324, -1.67]} scale={1.433} />
        <mesh geometry={nodes.polySurface428_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface429_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface430_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface431_lambert19_0.geometry} material={materials.lambert19} />
        <mesh geometry={nodes.polySurface432_lambert19_0.geometry} material={materials.lambert19} />
        <mesh geometry={nodes.polySurface433_lambert19_0.geometry} material={materials.lambert19} />
      </group>
      <group position={[5.297, -0.716, -1.302]} rotation={[-0.342, -0.967, -0.297]} scale={0.647}>
        <mesh geometry={nodes.polySurface404_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface405_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface406_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface407_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface408_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface409_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface410_lambert19_0.geometry} material={materials.lambert19} />
        <mesh geometry={nodes.polySurface411_lambert19_0.geometry} material={materials.lambert19} />
        <mesh geometry={nodes.polySurface412_lambert19_0.geometry} material={materials.lambert19} />
      </group>
      <group position={[-13.12, 0, 11.151]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.polySurface339_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface340_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface341_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface342_lambert18_0.geometry} material={materials.lambert18} position={[2.238, -1.089, -1.947]} scale={1.355} />
        <mesh geometry={nodes.polySurface343_lambert18_0.geometry} material={materials.lambert18} position={[2.216, -1.084, -1.916]} scale={1.355} />
        <mesh geometry={nodes.polySurface344_lambert18_0.geometry} material={materials.lambert18} position={[2.25, -1.097, -1.986]} scale={1.355} />
        <mesh geometry={nodes.polySurface345_lambert19_0.geometry} material={materials.lambert19} />
        <mesh geometry={nodes.polySurface346_lambert19_0.geometry} material={materials.lambert19} />
        <mesh geometry={nodes.polySurface347_lambert19_0.geometry} material={materials.lambert19} />
        <mesh geometry={nodes.polySurface348_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface349_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface350_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface351_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface352_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface353_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface354_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface355_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface356_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface357_lambert19_0.geometry} material={materials.lambert19} />
        <mesh geometry={nodes.polySurface358_lambert19_0.geometry} material={materials.lambert19} />
        <mesh geometry={nodes.polySurface359_lambert19_0.geometry} material={materials.lambert19} />
        <mesh geometry={nodes.polySurface360_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface361_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface362_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface363_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface364_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface365_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface366_lambert19_0.geometry} material={materials.lambert19} />
        <mesh geometry={nodes.polySurface367_lambert19_0.geometry} material={materials.lambert19} />
        <mesh geometry={nodes.polySurface368_lambert19_0.geometry} material={materials.lambert19} />
        <mesh geometry={nodes.polySurface369_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface370_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface371_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface372_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface373_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface374_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface375_lambert19_0.geometry} material={materials.lambert19} />
        <mesh geometry={nodes.polySurface376_lambert19_0.geometry} material={materials.lambert19} />
        <mesh geometry={nodes.polySurface377_lambert19_0.geometry} material={materials.lambert19} />
        <mesh geometry={nodes.polySurface378_lambert18_0.geometry} material={materials.lambert18} position={[6.146, -2.324, -4.528]} scale={1.816} />
        <mesh geometry={nodes.polySurface379_lambert18_0.geometry} material={materials.lambert18} position={[6.227, -2.312, -4.561]} scale={1.816} />
        <mesh geometry={nodes.polySurface380_lambert18_0.geometry} material={materials.lambert18} position={[6.126, -2.338, -4.471]} scale={1.816} />
        <mesh geometry={nodes.polySurface381_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface382_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface383_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface384_lambert19_0.geometry} material={materials.lambert19} />
        <mesh geometry={nodes.polySurface385_lambert19_0.geometry} material={materials.lambert19} />
        <mesh geometry={nodes.polySurface386_lambert19_0.geometry} material={materials.lambert19} />
        <mesh geometry={nodes.polySurface387_lambert20_0.geometry} material={materials.lambert20} />
        <mesh geometry={nodes.polySurface387_lambert21_0.geometry} material={materials.lambert21} />
        <mesh geometry={nodes.polySurface388_lambert19_0.geometry} material={materials.lambert19} position={[0.377, 2.246, -0.212]} />
      </group>
      <group position={[-15.441, 0, 7.362]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.polySurface286_lambert18_0.geometry} material={materials.lambert18} position={[4.897, -2.471, -2.794]} scale={1.65} />
        <mesh geometry={nodes.polySurface287_lambert18_0.geometry} material={materials.lambert18} position={[4.856, -2.483, -2.757]} scale={1.65} />
        <mesh geometry={nodes.polySurface288_lambert18_0.geometry} material={materials.lambert18} position={[4.799, -2.492, -2.699]} scale={1.65} />
        <mesh geometry={nodes.polySurface289_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface290_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface291_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface292_lambert19_0.geometry} material={materials.lambert19} />
        <mesh geometry={nodes.polySurface293_lambert19_0.geometry} material={materials.lambert19} />
        <mesh geometry={nodes.polySurface294_lambert19_0.geometry} material={materials.lambert19} />
        <mesh geometry={nodes.polySurface295_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface296_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface297_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface298_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface299_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface300_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface301_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface302_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface303_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface304_lambert19_0.geometry} material={materials.lambert19} />
        <mesh geometry={nodes.polySurface305_lambert19_0.geometry} material={materials.lambert19} />
        <mesh geometry={nodes.polySurface306_lambert19_0.geometry} material={materials.lambert19} />
        <mesh geometry={nodes.polySurface307_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface308_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface309_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface310_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface311_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface312_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface313_lambert19_0.geometry} material={materials.lambert19} />
        <mesh geometry={nodes.polySurface314_lambert19_0.geometry} material={materials.lambert19} />
        <mesh geometry={nodes.polySurface315_lambert19_0.geometry} material={materials.lambert19} />
        <mesh geometry={nodes.polySurface316_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface317_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface318_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface319_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface320_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface321_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface322_lambert19_0.geometry} material={materials.lambert19} />
        <mesh geometry={nodes.polySurface323_lambert19_0.geometry} material={materials.lambert19} />
        <mesh geometry={nodes.polySurface324_lambert19_0.geometry} material={materials.lambert19} />
        <mesh geometry={nodes.polySurface325_lambert18_0.geometry} material={materials.lambert18} position={[4.43, -1.649, -1.551]} scale={1.579} />
        <mesh geometry={nodes.polySurface326_lambert18_0.geometry} material={materials.lambert18} position={[4.453, -1.64, -1.494]} scale={1.579} />
        <mesh geometry={nodes.polySurface327_lambert18_0.geometry} material={materials.lambert18} position={[4.389, -1.658, -1.601]} scale={1.579} />
        <mesh geometry={nodes.polySurface328_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface329_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface330_lambert18_0.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.polySurface331_lambert19_0.geometry} material={materials.lambert19} />
        <mesh geometry={nodes.polySurface332_lambert19_0.geometry} material={materials.lambert19} />
        <mesh geometry={nodes.polySurface333_lambert19_0.geometry} material={materials.lambert19} />
        <mesh geometry={nodes.polySurface334_lambert20_0.geometry} material={materials.lambert20} />
        <mesh geometry={nodes.polySurface334_lambert21_0.geometry} material={materials.lambert21} />
        <mesh geometry={nodes.polySurface335_lambert19_0.geometry} material={materials.lambert19} position={[0.107, 2.289, 0.126]} />
        <mesh geometry={nodes.polySurface336_lambert19_0.geometry} material={materials.lambert19} position={[0.107, 2.289, 0.126]} />
        <mesh geometry={nodes.polySurface337_lambert19_0.geometry} material={materials.lambert19} position={[-0.03, 2.159, -0.078]} />
        <mesh geometry={nodes.polySurface338_lambert19_0.geometry} material={materials.lambert19} position={[0.08, 0.842, 0.144]} />
        <mesh geometry={nodes.polySurface389_lambert18_0.geometry} material={materials.lambert18} position={[1.129, 2.432, 3.721]} rotation={[0, -0.436, 0]} />
        <mesh geometry={nodes.polySurface390_lambert18_0.geometry} material={materials.lambert18} position={[1.129, 2.432, 3.721]} rotation={[0, -0.436, 0]} />
        <mesh geometry={nodes.polySurface391_lambert18_0.geometry} material={materials.lambert18} position={[1.129, 2.432, 3.721]} rotation={[0, -0.436, 0]} />
      </group>
      <group position={[5.392, 2.871, 0.934]} rotation={[0.227, 0, 0]} scale={[0.506, 0.506, 0.576]}>
        <mesh geometry={nodes.pCube236_lambert23_0.geometry} material={materials.lambert23} />
        <mesh geometry={nodes.pCube236_lambert25_0.geometry} material={materials.lambert25} />
        <mesh geometry={nodes.pCube236_lambert24_0.geometry} material={materials.lambert24} />
      </group>
      <group position={[4.622, 2.82, 1.154]} rotation={[0.227, 0, 0]} scale={[0.506, 0.506, 0.576]}>
        <mesh geometry={nodes.pCube237_lambert23_0.geometry} material={materials.lambert23} />
        <mesh geometry={nodes.pCube237_lambert25_0.geometry} material={materials.lambert25} />
        <mesh geometry={nodes.pCube237_lambert24_0.geometry} material={materials.lambert24} />
      </group>
      <group position={[3.757, 2.82, 1.154]} rotation={[0.227, 0, 0]} scale={[0.506, 0.506, 0.576]}>
        <mesh geometry={nodes.pCube238_lambert23_0.geometry} material={materials.lambert23} />
        <mesh geometry={nodes.pCube238_lambert25_0.geometry} material={materials.lambert25} />
        <mesh geometry={nodes.pCube238_lambert24_0.geometry} material={materials.lambert24} />
      </group>
      <group position={[2.99, 2.856, 0.999]} rotation={[0.227, 0, 0]} scale={[0.506, 0.506, 0.576]}>
        <mesh geometry={nodes.pCube239_lambert23_0.geometry} material={materials.lambert23} />
        <mesh geometry={nodes.pCube239_lambert25_0.geometry} material={materials.lambert25} />
        <mesh geometry={nodes.pCube239_lambert24_0.geometry} material={materials.lambert24} />
      </group>
      <group position={[2.302, 2.794, 1.267]} rotation={[0.227, 0, 0]} scale={[0.506, 0.506, 0.576]}>
        <mesh geometry={nodes.pCube240_lambert23_0.geometry} material={materials.lambert23} />
        <mesh geometry={nodes.pCube240_lambert25_0.geometry} material={materials.lambert25} />
        <mesh geometry={nodes.pCube240_lambert24_0.geometry} material={materials.lambert24} />
      </group>
      <group position={[-0.186, 3.933, -2.843]} rotation={[0.244, 0, 0]} scale={0.558}>
        <mesh geometry={nodes.pCube244_lambert26_0.geometry} material={materials.lambert26} />
        <mesh geometry={nodes.pCube244_lambert27_0.geometry} material={materials.lambert27} />
      </group>
      <group position={[-1.578, 3.935, -2.826]} rotation={[0.244, 0.122, 0]} scale={[0.578, 0.558, 0.578]}>
        <mesh geometry={nodes.pCube245_lambert26_0.geometry} material={materials.lambert26} />
        <mesh geometry={nodes.pCube245_lambert27_0.geometry} material={materials.lambert27} />
      </group>
      <group position={[-1.311, 4.287, -4.272]} rotation={[0.244, 0.07, 0]} scale={[0.618, 0.558, 0.618]}>
        <mesh geometry={nodes.pCube246_lambert26_0.geometry} material={materials.lambert26} />
        <mesh geometry={nodes.pCube246_lambert27_0.geometry} material={materials.lambert27} />
      </group>
      <group position={[0.467, 4.011, -3.163]} rotation={[0.244, -0.157, 0]} scale={[0.489, 0.558, 0.489]}>
        <mesh geometry={nodes.pCube247_lambert26_0.geometry} material={materials.lambert26} />
        <mesh geometry={nodes.pCube247_lambert27_0.geometry} material={materials.lambert27} />
      </group>
      <group position={[-0.515, 4.388, -3.226]} rotation={[0.244, 0, 0]} scale={0.558}>
        <mesh geometry={nodes.pCube248_lambert26_0.geometry} material={materials.lambert26} />
        <mesh geometry={nodes.pCube248_lambert27_0.geometry} material={materials.lambert27} />
      </group>
      <group position={[0, 0.017, -0.125]}>
        <mesh geometry={nodes.polySurface473_lambert28_0.geometry} material={materials.lambert28} />
        <mesh geometry={nodes.polySurface474_lambert30_0.geometry} material={materials.lambert30} />
        <mesh geometry={nodes.polySurface475_lambert30_0.geometry} material={materials.lambert30} />
        <mesh geometry={nodes.polySurface476_lambert30_0.geometry} material={materials.lambert30} />
        <mesh geometry={nodes.polySurface477_lambert30_0.geometry} material={materials.lambert30} />
        <mesh geometry={nodes.polySurface478_lambert30_0.geometry} material={materials.lambert30} />
      </group>
      <group position={[0.307, 0, 0]}>
        <mesh geometry={nodes.polySurface467_lambert28_0.geometry} material={materials.lambert28} />
        <mesh geometry={nodes.polySurface468_lambert29_0.geometry} material={materials.lambert29} />
        <mesh geometry={nodes.polySurface469_lambert29_0.geometry} material={materials.lambert29} />
        <mesh geometry={nodes.polySurface470_lambert29_0.geometry} material={materials.lambert29} />
        <mesh geometry={nodes.polySurface471_lambert29_0.geometry} material={materials.lambert29} />
        <mesh geometry={nodes.polySurface472_lambert29_0.geometry} material={materials.lambert29} />
      </group>
      <group position={[0.68, 0.016, -0.244]} rotation={[0, -0.087, 0]}>
        <mesh geometry={nodes.polySurface461_lambert28_0.geometry} material={materials.lambert28} />
        <mesh geometry={nodes.polySurface462_lambert30_0.geometry} material={materials.lambert30} />
        <mesh geometry={nodes.polySurface463_lambert30_0.geometry} material={materials.lambert30} />
        <mesh geometry={nodes.polySurface464_lambert30_0.geometry} material={materials.lambert30} />
        <mesh geometry={nodes.polySurface465_lambert30_0.geometry} material={materials.lambert30} />
        <mesh geometry={nodes.polySurface466_lambert30_0.geometry} material={materials.lambert30} />
      </group>
      <group position={[-0.319, 0.017, -0.044]} rotation={[0, 0.07, 0]}>
        <mesh geometry={nodes.polySurface485_lambert28_0.geometry} material={materials.lambert28} />
        <mesh geometry={nodes.polySurface486_lambert29_0.geometry} material={materials.lambert29} />
        <mesh geometry={nodes.polySurface487_lambert29_0.geometry} material={materials.lambert29} />
        <mesh geometry={nodes.polySurface488_lambert29_0.geometry} material={materials.lambert29} />
        <mesh geometry={nodes.polySurface489_lambert29_0.geometry} material={materials.lambert29} />
        <mesh geometry={nodes.polySurface490_lambert29_0.geometry} material={materials.lambert29} />
      </group>
      <group position={[-0.217, 0.105, 0.2]} rotation={[0, 0.087, 0]}>
        <mesh geometry={nodes.polySurface479_lambert28_0.geometry} material={materials.lambert28} />
        <mesh geometry={nodes.polySurface480_lambert29_0.geometry} material={materials.lambert29} />
        <mesh geometry={nodes.polySurface481_lambert29_0.geometry} material={materials.lambert29} />
        <mesh geometry={nodes.polySurface482_lambert29_0.geometry} material={materials.lambert29} />
        <mesh geometry={nodes.polySurface483_lambert29_0.geometry} material={materials.lambert29} />
        <mesh geometry={nodes.polySurface484_lambert29_0.geometry} material={materials.lambert29} />
      </group>
      <group position={[0.268, 0.09, -0.152]} rotation={[0, -0.07, 0]}>
        <mesh geometry={nodes.polySurface455_lambert28_0.geometry} material={materials.lambert28} />
        <mesh geometry={nodes.polySurface456_lambert30_0.geometry} material={materials.lambert30} />
        <mesh geometry={nodes.polySurface457_lambert30_0.geometry} material={materials.lambert30} />
        <mesh geometry={nodes.polySurface458_lambert30_0.geometry} material={materials.lambert30} />
        <mesh geometry={nodes.polySurface459_lambert30_0.geometry} material={materials.lambert30} />
        <mesh geometry={nodes.polySurface460_lambert30_0.geometry} material={materials.lambert30} />
      </group>
      <group position={[-0.372, 0.016, -0.009]} rotation={[0, -0.017, 0]}>
        <mesh geometry={nodes.polySurface491_lambert28_0.geometry} material={materials.lambert28} />
        <mesh geometry={nodes.polySurface492_lambert30_0.geometry} material={materials.lambert30} />
        <mesh geometry={nodes.polySurface493_lambert30_0.geometry} material={materials.lambert30} />
        <mesh geometry={nodes.polySurface494_lambert30_0.geometry} material={materials.lambert30} />
        <mesh geometry={nodes.polySurface495_lambert30_0.geometry} material={materials.lambert30} />
        <mesh geometry={nodes.polySurface496_lambert30_0.geometry} material={materials.lambert30} />
      </group>
      <mesh geometry={nodes.pCube1_lambert35_0.geometry} material={materials.lambert35} position={[0, 0, -0.601]} scale={[10.357, 0.328, 10.357]} />
      <mesh geometry={nodes.pCube3_lambert12_0.geometry} material={materials.lambert12} position={[0, 8.077, -0.657]} rotation={[0.384, 0, 0]} scale={[12.076, 0.011, 7.459]} />
      <mesh geometry={nodes.pCylinder1_phong6_0.geometry} material={materials.phong6} position={[0, 11.797, -3.159]} rotation={[0, 0, -Math.PI / 2]} scale={[0.203, 0.221, 0.203]} />
      <mesh geometry={nodes.pCube5_lambert12_0.geometry} material={materials.lambert12} />
      <mesh geometry={nodes.pCube4_lambert31_0.geometry} material={materials.lambert31} position={[0, 7.131, -3.191]} scale={[9.128, 1, 3.918]} />
      <mesh geometry={nodes.pCube121_lambert12_0.geometry} material={materials.lambert12} position={[0, 0, -6.403]} rotation={[-Math.PI, 0, Math.PI]} scale={[-1, 1, 1]} />
      <mesh geometry={nodes.pCylinder13_phong6_0.geometry} material={materials.phong6} position={[-7.199, 11.763, 3.555]} rotation={[Math.PI, 1.518, Math.PI / 2]} scale={[0.186, 0.05, 0.186]} />
      <mesh geometry={nodes.pCube19_lambert33_0.geometry} material={materials.lambert33} position={[-0.087, -0.066, 0]} />
      <mesh geometry={nodes.pCube42_lambert31_0.geometry} material={materials.lambert31} position={[-1.937, 0.642, -1.441]} scale={[10.311, 1, 7.459]} />
      <mesh geometry={nodes.pCube44_lambert32_0.geometry} material={materials.lambert32} position={[2.147, 0.287, 1.949]} rotation={[0, Math.PI / 2, 0]} scale={[10.311, 1, 7.459]} />
      <mesh geometry={nodes.pCube45_lambert34_0.geometry} material={materials.lambert34} position={[2.147, 2.239, 2.242]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[10.311, 1, 7.459]} />
      <mesh geometry={nodes.pCube47_lambert33_0.geometry} material={materials.lambert33} position={[0.375, 3.221, 2.05]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[10.311, 1, 15.538]} />
      <mesh geometry={nodes.pCube48_lambert3_0.geometry} material={materials.lambert3} position={[-1.255, 3.221, 2.156]} rotation={[0, -0.017, -Math.PI / 2]} scale={[10.311, 1, 7.459]} />
      <mesh geometry={nodes.pCube49_lambert44_0.geometry} material={materials.lambert44} position={[3.094, 2.475, 2.021]} rotation={[-1.344, Math.PI / 2, 0]} scale={[10.311, 1, 7.459]} />
      <mesh geometry={nodes.pCube50_lambert32_0.geometry} material={materials.lambert32} position={[-0.629, 2.479, 2.021]} rotation={[-1.344, Math.PI / 2, 0]} scale={[10.311, 1, 7.459]} />
      <mesh geometry={nodes.pCylinder7_lambert36_0.geometry} material={materials.lambert36} position={[-7.135, 1.07, 3.543]} scale={0.113} />
      <mesh geometry={nodes.pCube51_lambert32_0.geometry} material={materials.lambert32} position={[-7.163, 8.362, 3.528]} scale={[1, 1, 1.322]} />
      <mesh geometry={nodes.pCube52_lambert31_0.geometry} material={materials.lambert31} />
      <mesh geometry={nodes.pCube53_lambert31_0.geometry} material={materials.lambert31} position={[0, 6.921, -0.601]} scale={[10.357, 0.328, 10.357]} />
      <mesh geometry={nodes.pCube83_lambert32_0.geometry} material={materials.lambert32} />
      <mesh geometry={nodes.pCube62_lambert32_0.geometry} material={materials.lambert32} />
      <mesh geometry={nodes.pCube10_lambert32_0.geometry} material={materials.lambert32} />
      <mesh geometry={nodes.pCube84_lambert32_0.geometry} material={materials.lambert32} position={[5.596, 0, 0]} />
      <mesh geometry={nodes.pCube85_lambert33_0.geometry} material={materials.lambert33} position={[5.51, -0.066, 0]} />
      <mesh geometry={nodes.pCube87_lambert33_0.geometry} material={materials.lambert33} position={[-5.577, 6.906, 2.633]} scale={[0.228, 0.076, 10.357]} />
      <mesh geometry={nodes.pCube88_lambert33_0.geometry} material={materials.lambert33} position={[4.565, 6.807, 1.719]} rotation={[0, Math.PI / 2, 0]} scale={[0.228, 0.123, 22.207]} />
      <mesh geometry={nodes.pCube89_lambert33_0.geometry} material={materials.lambert33} position={[4.565, 6.807, 0.764]} rotation={[0, Math.PI / 2, 0]} scale={[0.228, 0.123, 22.207]} />
      <mesh geometry={nodes.pCube90_lambert33_0.geometry} material={materials.lambert33} position={[4.565, 6.807, -0.066]} rotation={[0, Math.PI / 2, 0]} scale={[0.228, 0.123, 22.207]} />
      <mesh geometry={nodes.pCube91_lambert33_0.geometry} material={materials.lambert33} position={[-2.468, 6.906, 2.909]} scale={[0.228, 0.076, 10.357]} />
      <mesh geometry={nodes.pCube92_lambert33_0.geometry} material={materials.lambert33} position={[0.486, 6.906, 2.813]} scale={[0.228, 0.076, 10.357]} />
      <mesh geometry={nodes.pCube93_lambert33_0.geometry} material={materials.lambert33} position={[5.648, 6.906, 2.861]} scale={[0.228, 0.076, 10.357]} />
      <mesh geometry={nodes.pCube94_lambert33_0.geometry} material={materials.lambert33} position={[3.123, 6.906, 2.733]} scale={[0.228, 0.076, 10.357]} />
      <mesh geometry={nodes.pCube95_lambert33_0.geometry} material={materials.lambert33} position={[0.466, 8.386, -1.844]} rotation={[0.384, 0, 0]} scale={[0.172, 0.014, 9.764]} />
      <mesh geometry={nodes.pCube96_lambert33_0.geometry} material={materials.lambert33} position={[3.139, 8.386, -1.844]} rotation={[0.384, 0, 0]} scale={[0.172, 0.014, 9.764]} />
      <mesh geometry={nodes.pCube97_lambert33_0.geometry} material={materials.lambert33} position={[5.668, 8.386, -1.844]} rotation={[0.384, 0, 0]} scale={[0.172, 0.014, 9.764]} />
      <mesh geometry={nodes.pCube98_lambert33_0.geometry} material={materials.lambert33} position={[-2.456, 8.386, -1.844]} rotation={[0.384, 0, 0]} scale={[0.172, 0.014, 9.764]} />
      <mesh geometry={nodes.pCube99_lambert33_0.geometry} material={materials.lambert33} position={[-5.596, 8.386, -1.844]} rotation={[0.384, 0, 0]} scale={[0.172, 0.014, 9.764]} />
      <mesh geometry={nodes.pCube106_lambert33_0.geometry} material={materials.lambert33} position={[4.565, 6.807, -1.076]} rotation={[0, Math.PI / 2, 0]} scale={[0.228, 0.123, 22.207]} />
      <mesh geometry={nodes.pCube111_lambert33_0.geometry} material={materials.lambert33} />
      <mesh geometry={nodes.pCube112_lambert32_0.geometry} material={materials.lambert32} />
      <mesh geometry={nodes.polySurface53_lambert33_0.geometry} material={materials.lambert33} />
      <mesh geometry={nodes.polySurface64_phong6_0.geometry} material={materials.phong6} position={[-0.287, -0.303, -3.095]} rotation={[Math.PI / 10, 0, 0]} scale={[1, 1, 1.177]} />
      <mesh geometry={nodes.polySurface65_lambert4_0.geometry} material={materials.lambert4} position={[-6.256, -0.467, -2.59]} rotation={[Math.PI / 10, 0, 0]} scale={[1.009, 1, 1]} />
      <mesh geometry={nodes.polySurface77_phong6_0.geometry} material={materials.phong6} position={[-12.107, -0.421, -2.732]} rotation={[Math.PI / 10, 0, 0]} scale={[1, 1, 1.084]} />
      <mesh geometry={nodes.polySurface78_lambert4_0.geometry} material={materials.lambert4} position={[-0.287, -0.681, -2.819]} rotation={[0.157, 0, 0]} scale={[1, 1, 1.142]} />
      <mesh geometry={nodes.polySurface79_phong6_0.geometry} material={materials.phong6} position={[-6.256, -0.361, -3.551]} rotation={[0.227, 0, 0]} scale={[1.009, 1, 1.347]} />
      <mesh geometry={nodes.polySurface80_lambert4_0.geometry} material={materials.lambert4} position={[-12.107, -0.761, -2.318]} rotation={[0.157, 0, 0]} />
      <mesh geometry={nodes.polySurface81_lambert4_0.geometry} material={materials.lambert4} position={[-0.287, -0.603, -2.602]} rotation={[0.157, 0, 0]} scale={[1, 1, 0.699]} />
      <mesh geometry={nodes.polySurface82_phong6_0.geometry} material={materials.phong6} position={[-6.256, -0.603, -3.027]} rotation={[0.14, 0, 0]} scale={[1.009, 1, 1]} />
      <mesh geometry={nodes.polySurface83_phong6_0.geometry} material={materials.phong6} position={[-12.107, -0.387, -3.349]} rotation={[0.209, 0, 0]} scale={[1, 1, 0.812]} />
      <mesh geometry={nodes.polySurface84_phong6_0.geometry} material={materials.phong6} position={[-0.287, 0.228, -4.886]} rotation={[0.297, 0, 0]} scale={[1, 1, 0.819]} />
      <mesh geometry={nodes.polySurface85_lambert4_0.geometry} material={materials.lambert4} position={[-6.256, 0.264, -5.006]} rotation={[0.297, 0, 0]} scale={[1.009, 1, 0.928]} />
      <mesh geometry={nodes.polySurface86_lambert4_0.geometry} material={materials.lambert4} position={[-12.107, 0.255, -4.974]} rotation={[0.297, 0, 0]} scale={[1, 1, 0.819]} />
      <mesh geometry={nodes.polySurface646_phong6_0.geometry} material={materials.phong6} />
      <mesh geometry={nodes.polySurface647_lambert4_0.geometry} material={materials.lambert4} />
      <mesh geometry={nodes.polySurface648_phong6_0.geometry} material={materials.phong6} />
      <mesh geometry={nodes.polySurface649_lambert4_0.geometry} material={materials.lambert4} />
      <mesh geometry={nodes.polySurface650_phong6_0.geometry} material={materials.phong6} />
      <mesh geometry={nodes.polySurface651_lambert4_0.geometry} material={materials.lambert4} />
      <mesh geometry={nodes.pCylinder14_lambert1_0.geometry} material={materials.lambert1} position={[-7.142, 11.63, 4.12]} scale={[0.035, 0.005, 0.035]} />
      <mesh geometry={nodes.pCylinder15_lambert1_0.geometry} material={materials.lambert1} position={[-7.142, 11.63, 2.976]} scale={[0.035, 0.005, 0.035]} />
      <mesh geometry={nodes.pCube141_lambert12_0.geometry} material={materials.lambert12} position={[2.004, 8.366, 1.606]} rotation={[0.925, 0, 0]} scale={[0.379, 1.878, 0.188]} />
      <mesh geometry={nodes.pCube142_lambert12_0.geometry} material={materials.lambert12} position={[-1.66, 8.366, 1.606]} rotation={[0.925, 0, 0]} scale={[0.379, 1.878, 0.188]} />
      <mesh geometry={nodes.pCube143_lambert37_0.geometry} material={materials.lambert37} position={[-4.08, 6.264, 1.319]} scale={[3.614, 1, 1]} />
      <mesh geometry={nodes.polySurface502_lambert40_0.geometry} material={materials.lambert40} />
      <mesh geometry={nodes.polySurface503_lambert32_0.geometry} material={materials.lambert32} />
      <mesh geometry={nodes.polySurface504_lambert32_0.geometry} material={materials.lambert32} />
      <mesh geometry={nodes.polySurface505_phong5_0.geometry} material={materials.phong5} />
      <mesh geometry={nodes.polySurface506_lambert32_0.geometry} material={materials.lambert32} />
      <mesh geometry={nodes.polySurface507_lambert32_0.geometry} material={materials.lambert32} />
      <mesh geometry={nodes.polySurface508_lambert32_0.geometry} material={materials.lambert32} />
      <mesh geometry={nodes.polySurface509_lambert32_0.geometry} material={materials.lambert32} />
      <mesh geometry={nodes.polySurface510_lambert32_0.geometry} material={materials.lambert32} />
      <mesh geometry={nodes.polySurface511_lambert32_0.geometry} material={materials.lambert32} />
      <mesh geometry={nodes.polySurface512_lambert32_0.geometry} material={materials.lambert32} />
      <mesh geometry={nodes.pCube153_lambert38_0.geometry} material={materials.lambert38} position={[0, 1.357, -0.06]} scale={[1, 0.802, 1]} />
      <mesh geometry={nodes.polySurface539_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface540_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface541_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface542_lambert42_0.geometry} material={materials.lambert42} />
      <mesh geometry={nodes.polySurface543_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface544_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface545_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface546_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface547_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface548_lambert42_0.geometry} material={materials.lambert42} />
      <mesh geometry={nodes.polySurface549_lambert42_0.geometry} material={materials.lambert42} />
      <mesh geometry={nodes.polySurface550_lambert42_0.geometry} material={materials.lambert42} />
      <mesh geometry={nodes.polySurface551_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface552_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface553_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface554_lambert42_0.geometry} material={materials.lambert42} />
      <mesh geometry={nodes.polySurface555_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface556_lambert42_0.geometry} material={materials.lambert42} />
      <mesh geometry={nodes.polySurface557_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface558_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface559_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface560_lambert42_0.geometry} material={materials.lambert42} />
      <mesh geometry={nodes.polySurface561_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface562_lambert42_0.geometry} material={materials.lambert42} />
      <mesh geometry={nodes.polySurface563_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface564_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface565_lambert42_0.geometry} material={materials.lambert42} />
      <mesh geometry={nodes.polySurface566_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface567_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface568_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface569_lambert42_0.geometry} material={materials.lambert42} />
      <mesh geometry={nodes.polySurface570_lambert42_0.geometry} material={materials.lambert42} />
      <mesh geometry={nodes.polySurface571_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface572_lambert42_0.geometry} material={materials.lambert42} />
      <mesh geometry={nodes.polySurface573_lambert42_0.geometry} material={materials.lambert42} />
      <mesh geometry={nodes.polySurface574_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface575_lambert42_0.geometry} material={materials.lambert42} />
      <mesh geometry={nodes.polySurface576_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface577_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface578_lambert42_0.geometry} material={materials.lambert42} />
      <mesh geometry={nodes.polySurface579_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface580_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface581_lambert42_0.geometry} material={materials.lambert42} />
      <mesh geometry={nodes.polySurface582_lambert42_0.geometry} material={materials.lambert42} />
      <mesh geometry={nodes.polySurface583_lambert42_0.geometry} material={materials.lambert42} />
      <mesh geometry={nodes.polySurface584_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface585_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface586_lambert42_0.geometry} material={materials.lambert42} />
      <mesh geometry={nodes.polySurface587_lambert42_0.geometry} material={materials.lambert42} />
      <mesh geometry={nodes.polySurface588_lambert42_0.geometry} material={materials.lambert42} />
      <mesh geometry={nodes.polySurface589_lambert42_0.geometry} material={materials.lambert42} />
      <mesh geometry={nodes.polySurface590_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface591_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface592_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface593_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface594_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface595_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface596_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface597_lambert42_0.geometry} material={materials.lambert42} />
      <mesh geometry={nodes.polySurface598_lambert42_0.geometry} material={materials.lambert42} />
      <mesh geometry={nodes.polySurface599_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface600_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface601_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface602_lambert42_0.geometry} material={materials.lambert42} />
      <mesh geometry={nodes.polySurface603_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface604_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface605_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface606_lambert42_0.geometry} material={materials.lambert42} />
      <mesh geometry={nodes.polySurface607_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface608_lambert42_0.geometry} material={materials.lambert42} />
      <mesh geometry={nodes.polySurface609_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface610_lambert42_0.geometry} material={materials.lambert42} />
      <mesh geometry={nodes.polySurface611_lambert42_0.geometry} material={materials.lambert42} />
      <mesh geometry={nodes.polySurface612_lambert42_0.geometry} material={materials.lambert42} />
      <mesh geometry={nodes.polySurface613_lambert42_0.geometry} material={materials.lambert42} />
      <mesh geometry={nodes.polySurface614_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface615_lambert42_0.geometry} material={materials.lambert42} />
      <mesh geometry={nodes.polySurface616_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface617_lambert42_0.geometry} material={materials.lambert42} />
      <mesh geometry={nodes.polySurface618_lambert42_0.geometry} material={materials.lambert42} />
      <mesh geometry={nodes.polySurface619_lambert42_0.geometry} material={materials.lambert42} />
      <mesh geometry={nodes.polySurface620_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface621_lambert42_0.geometry} material={materials.lambert42} />
      <mesh geometry={nodes.polySurface622_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface623_lambert42_0.geometry} material={materials.lambert42} />
      <mesh geometry={nodes.polySurface624_lambert42_0.geometry} material={materials.lambert42} />
      <mesh geometry={nodes.polySurface625_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface626_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface627_lambert42_0.geometry} material={materials.lambert42} />
      <mesh geometry={nodes.polySurface628_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface629_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface630_lambert42_0.geometry} material={materials.lambert42} />
      <mesh geometry={nodes.polySurface631_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface632_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface633_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface634_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface635_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface636_lambert42_0.geometry} material={materials.lambert42} />
      <mesh geometry={nodes.polySurface637_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface638_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface639_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface640_lambert42_0.geometry} material={materials.lambert42} />
      <mesh geometry={nodes.polySurface641_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface642_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface643_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface644_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.polySurface645_lambert41_0.geometry} material={materials.lambert41} />
      <mesh geometry={nodes.pCube204_lambert12_0.geometry} material={materials.lambert12} position={[2.459, 0, -0.92]} />
      <mesh geometry={nodes.polySurface240_phong4_0.geometry} material={materials.phong4} position={[0.433, 3.075, -2.839]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 1, 1.177]} />
      <mesh geometry={nodes.polySurface241_phong4_0.geometry} material={materials.phong4} position={[-0.676, 3.159, 8.122]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1, 1, 1.177]} />
      <mesh geometry={nodes.polySurface242_phong4_0.geometry} material={materials.phong4} position={[-0.64, 3.075, 2.288]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1, 1, 1.177]} />
      <mesh geometry={nodes.polySurface243_phong4_0.geometry} material={materials.phong4} position={[-0.676, 3.075, -3.559]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1, 1, 1.177]} />
      <mesh geometry={nodes.polySurface244_phong4_0.geometry} material={materials.phong4} position={[-12.799, 3.24, -2.839]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 1, 1.177]} />
      <mesh geometry={nodes.polySurface245_phong4_0.geometry} material={materials.phong4} position={[0.555, 3.173, -4.119]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[1, 1, 1.177]} />
      <mesh geometry={nodes.polySurface246_phong4_0.geometry} material={materials.phong4} position={[0.591, 3.075, 1.728]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[1, 1, 1.177]} />
      <mesh geometry={nodes.polySurface247_phong4_0.geometry} material={materials.phong4} position={[0.591, 3.075, -9.952]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[1, 1, 1.177]} />
      <mesh geometry={nodes.polySurface248_phong4_0.geometry} material={materials.phong4} position={[-0.483, 3.105, 1.066]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[1, 1, 1.177]} />
      <mesh geometry={nodes.polySurface249_phong4_0.geometry} material={materials.phong4} position={[5.322, 3.075, 1.066]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[1, 1, 1.177]} />
      <mesh geometry={nodes.polySurface250_phong4_0.geometry} material={materials.phong4} position={[11.159, 3.107, 1.066]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[1, 1, 1.177]} />
      <mesh geometry={nodes.pCylinder39_phong1_0.geometry} material={materials.phong1} />
      <mesh geometry={nodes.pCylinder39_lambert6_0.geometry} material={materials.lambert6} />
      <mesh geometry={nodes.pCylinder39_lambert5_0.geometry} material={materials.lambert5} />
      <mesh geometry={nodes.pCylinder39_lambert7_0.geometry} material={materials.lambert7} />
      <mesh geometry={nodes.polySurface257_lambert7_0.geometry} material={materials.lambert7} />
      <mesh geometry={nodes.polySurface257_phong1_0.geometry} material={materials.phong1} />
      <mesh geometry={nodes.polySurface257_lambert6_0.geometry} material={materials.lambert6} />
      <mesh geometry={nodes.polySurface257_lambert5_0.geometry} material={materials.lambert5} />
      <mesh geometry={nodes.polySurface258_lambert7_0.geometry} material={materials.lambert7} />
      <mesh geometry={nodes.polySurface258_phong1_0.geometry} material={materials.phong1} />
      <mesh geometry={nodes.polySurface258_lambert6_0.geometry} material={materials.lambert6} />
      <mesh geometry={nodes.polySurface258_lambert5_0.geometry} material={materials.lambert5} />
      <mesh geometry={nodes.pDisc1_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.pCube214_lambert20_0.geometry} material={materials.lambert20} />
      <mesh geometry={nodes.pCube214_lambert21_0.geometry} material={materials.lambert21} />
      <mesh geometry={nodes.polySurface413_lambert18_0.geometry} material={materials.lambert18} position={[-3.909, -2.096, -3.022]} scale={1.551} />
      <mesh geometry={nodes.polySurface414_lambert18_0.geometry} material={materials.lambert18} position={[-3.878, -2.107, -2.964]} scale={1.551} />
      <mesh geometry={nodes.polySurface415_lambert18_0.geometry} material={materials.lambert18} position={[-3.828, -2.114, -2.915]} scale={1.551} />
      <mesh geometry={nodes.polySurface416_lambert18_0.geometry} material={materials.lambert18} />
      <mesh geometry={nodes.polySurface417_lambert18_0.geometry} material={materials.lambert18} />
      <mesh geometry={nodes.polySurface418_lambert18_0.geometry} material={materials.lambert18} />
      <mesh geometry={nodes.polySurface419_lambert19_0.geometry} material={materials.lambert19} />
      <mesh geometry={nodes.polySurface420_lambert19_0.geometry} material={materials.lambert19} />
      <mesh geometry={nodes.polySurface421_lambert19_0.geometry} material={materials.lambert19} />
      <mesh geometry={nodes.polySurface422_lambert18_0.geometry} material={materials.lambert18} />
      <mesh geometry={nodes.polySurface423_lambert18_0.geometry} material={materials.lambert18} />
      <mesh geometry={nodes.polySurface424_lambert18_0.geometry} material={materials.lambert18} />
      <mesh geometry={nodes.polySurface284_lambert19_0.geometry} material={materials.lambert19} position={[0.207, 3.354, -0.148]} />
      <mesh geometry={nodes.polySurface393_lambert18_0.geometry} material={materials.lambert18} position={[6.807, -3.84, -4.846]} scale={1.831} />
      <mesh geometry={nodes.pCube230_lambert22_0.geometry} material={materials.lambert22} position={[5.979, 6.295, 4.945]} rotation={[1.918, -0.304, -0.239]} scale={0.122} />
      <mesh geometry={nodes.pCylinder46_phong2_0.geometry} material={materials.phong2} position={[8.134, 3.128, 1.269]} rotation={[0, 0, -0.035]} scale={0.461} />
      <mesh geometry={nodes.pCylinder49_lambert18_0.geometry} material={materials.lambert18} position={[7.044, 6.76, 2.399]} rotation={[-0.627, -1.254, -0.765]} scale={0.026} />
      <mesh geometry={nodes.pCylinder50_lambert18_0.geometry} material={materials.lambert18} position={[6.854, 6.975, 2.432]} rotation={[-0.053, -0.871, -0.121]} scale={0.026} />
      <mesh geometry={nodes.pCube231_lambert22_0.geometry} material={materials.lambert22} position={[7.404, 7.468, 3.345]} rotation={[-0.599, -1.27, -1.94]} scale={0.107} />
      <mesh geometry={nodes.pCube232_lambert39_0.geometry} material={materials.lambert39} position={[5.598, 6.457, 4.715]} rotation={[1.521, -0.188, -0.337]} scale={0.146} />
      <mesh geometry={nodes.pCube233_lambert22_0.geometry} material={materials.lambert22} position={[6.713, 7.478, 3.757]} rotation={[0.915, -0.5, -0.802]} scale={0.105} />
      <mesh geometry={nodes.pCube234_lambert39_0.geometry} material={materials.lambert39} position={[5.879, 6.654, 4.003]} rotation={[1.073, 0.165, -0.61]} scale={0.136} />
      <mesh geometry={nodes.pCube235_lambert32_0.geometry} material={materials.lambert32} />
      <mesh geometry={nodes.pCube249_phong3_0.geometry} material={materials.phong3} position={[1.98, 9.236, -1.205]} scale={[1.371, 1, 0.021]} />
      <mesh geometry={nodes.pCube250_phong3_0.geometry} material={materials.phong3} position={[3.665, 9.236, -1.205]} scale={[1.371, 1, 0.021]} />
      <mesh geometry={nodes.pCube251_phong3_0.geometry} material={materials.phong3} position={[-1.942, 9.236, -1.205]} scale={[1.371, 1, 0.021]} />
      <mesh geometry={nodes.pCube252_phong3_0.geometry} material={materials.phong3} position={[-3.627, 9.236, -1.205]} scale={[1.371, 1, 0.021]} />
      <mesh geometry={nodes.pasted__polySurface1549_pasted__phong17_0.geometry} material={materials.pasted__phong17} position={[-2.036, -2.657, -1.584]} rotation={[0, -0.279, 0]} />
      <mesh geometry={nodes.pCube253_lambert43_0.geometry} material={materials.lambert43} position={[-0.772, -3.156, 0.733]} scale={[1, 0.802, 1]} />
    </group>
  )
}

useGLTF.preload('/models/japanese_restaurant.glb')
